### PR TITLE
fix: upcoming vctrs ptype checks

### LINKED ISSUE #392: Issue with `names()` on empty pkg_ref
``` r
names(riskmetric::pkg_ref("utils"))
#>  [1] "bug_reports"        "bug_reports_host"  
#>  [3] "bug_reports_url"    "description"       
#>  [5] "downloads"          "examples"          
#>  [7] "help"               "help_aliases"      
#>  [9] "license"            "maintainer"        
#> [11] "news"               "r_cmd_check"       
#> [13] "release_date"       "remote_checks"     
#> [15] "source_control_url" "vignettes"         
#> [17] "website_urls"       "path"              
#> [19] "source"             "version"           
#> [21] "name"
```

``` r
names(riskmetric::pkg_ref())
#> Error in class(x) <- "environment": "environment" can only be set as the class if the object has this type; found "logical"
```

I think there is something wrong with the empty pkg-ref case that causes this error.

This came up when doing revdeps with https://github.com/r-lib/vctrs/pull/2112 due to the `ptype = pkg_ref()` call here https://github.com/pharmaR/riskmetric/blob/960b4a29d8d0f69b3630b9805b7da39d516c2f67/R/pkg_ref_class_coersion.R#L6 and the fact that `new_list_of()` now calls `vec_ptype(ptype)` on the `ptype` argument to ensure it is a `ptype`, and internally that needs to look at the `names()` of that object, which causes this odd failure.

We plan to release vctrs in early Jan, FYI

### PR DESCRIPTION
**Pull request by dgkf**
Supersedes #393 
Closes #392 

After discovering another issue in a vignette, I realized there's a much simpler solution that I think is more conventional anyways.

### CODE REVIEW

File: R/utils_memoised.R [hunk 1]
```diff
@@ -69,8 +69,6 @@ memoise_bioc_mirrors <- memoise::memoise({
 
 #' @importFrom memoise memoise
 memoise_available_packages <- memoise::memoise({
-  Sys.sleep(20)
-
```
Comment (dgkf) [inline R/utils_memoised.R]: This one's embarrassing. `git blame` reveals that this is residual from noneother than myself. I don't know exactly why I added it, but I assume it was to test the memoisation. No better time than the present to fix it.

File: R/pkg_ref_class_coersion.R [hunk 2]
```diff
@@ -3,7 +3,7 @@
 #' @export
 as_tibble.pkg_ref <- function(x, ...) {
   as_tibble(vctrs::new_list_of(list(x),
-    ptype = pkg_ref(),
+    ptype = list(),
```
Comment (dgkf) [inline R/pkg_ref_class_coersion.R]: `ptype` needs to be a vector type indicating what type of vector-ish object this should be, not a prototype element. This is enforced in the upcoming `vctrs` release and needs to be fixed before early january.

**Review by llrs-roche — APPROVED** [review]
Haven't tested locally with the new vctrs but it looks good.
